# Generated by Django 5.0.6 on 2025-12-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stock_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_modification',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='modified_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
