# Generated by Django 5.0.6 on 2025-12-27 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_last_modification_stock_last_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.IntegerField()),
                ('adjusted_quantity', models.IntegerField()),
                ('adjustment_type', models.CharField(choices=[('correction', 'Correction'), ('damage', 'Damage'), ('loss', 'Loss'), ('found', 'Found'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('adjusted_by', models.CharField(max_length=100)),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-adjusted_at'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('change_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('edit', 'Edit'), ('delete', 'Delete'), ('restore', 'Restore')], max_length=20)),
                ('changed_by', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity', 'is_deleted'], name='inventory_s_quantit_a5b855_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_modified'], name='inventory_s_last_mo_447dbf_idx'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.stock'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['stock', '-adjusted_at'], name='inventory_s_stock_i_a3e2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_type', '-adjusted_at'], name='inventory_s_adjustm_a3c0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['stock', '-changed_at'], name='inventory_s_stock_i_6d56ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['change_type', '-changed_at'], name='inventory_s_change__0b28c5_idx'),
        ),
    ]
