# Generated by Django 5.0.6 on 2025-12-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockadjustment_stockhistory_alter_stock_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='new_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='previous_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='new_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='previous_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
